### PR TITLE
Bring status output to current web standards

### PR DESCRIPTION
**Pull request by szarka**
Minor cleanup of HTML/CSS for status pages:
- remove deprecated attribute on style element
- replace obsolete CENTER attribute using CSS classes

All HTML+CSS now validates cleanly. May be minor changes to spacing.

### CODE REVIEW

**Comment by jesterhodl** [comment]
Would this also make sense for mobiles? I have happened to access datum from a mobile.
```<meta name="viewport" content="width=device-width">```

Lighthouse says: 
> A <meta name="viewport"> not only optimizes your app for mobile screen sizes, but also prevents [a 300 millisecond delay to user input](https://developer.chrome.com/blog/300ms-tap-delay-gone-away/). [Learn more about using the viewport meta tag](https://developer.chrome.com/docs/lighthouse/pwa/viewport/).

**Comment by wizkid057** [comment]
> Minor cleanup of HTML/CSS for status pages:
> 
> * remove deprecated attribute on style element
> * replace obsolete CENTER attribute using CSS classes
> 
> All HTML+CSS now validates cleanly. May be minor changes to spacing.

utACK - Minor changes, all seem fine.

> Would this also make sense for mobiles? I have happened to access datum from a mobile. `<meta name="viewport" content="width=device-width">`

Admittedly my HTML-fu is not entirely up to date these days, and I don't know the full ramifications for this, especially on wide pages like the client list.  I do believe the latency thing is a quirk of old mobile browsers, though, and not something that modern implementations suffer from.

**Comment by szarka** [comment]
I was trying to keep the changes minimal to not step on any toes or get over my skis. But I do think a small change could on mobile. Will add this in a minute:

```
<meta name="viewport" content="width=device-width, initial-scale=1">
```

**Comment by szarka** [comment]
OK, changes made, tested, and validated. This looks better on my Android phone. Anybody have an iPhone and want to check?

**Comment by luke-jr** [comment]
Typo in commit message for 777aaf0

**Comment by szarka** [comment]
> Typo in commit message for [777aaf0](https://github.com/OCEAN-xyz/datum_gateway/commit/777aaf096a6e86a67f825aaee8fc92f58d1bfb7b)

TIL how to fix a typo. LOL

**Comment by szarka** [comment]
There's one more issue I see with mobile: because the clients page is so wide, it still spills out of the viewport. To be clear, it was worse without the change, but it's still a bit messy. Not sure there's a good fix, really.

But one thing that is fixable is that the "Total active hashrate estimate" piece could be viewable if left-aligned instead of centered. What do you think, @wizkid057?

**Comment by szarka** [comment]
Not hearing any other suggestions, and not wanting to get into trying to actually redesign the pages, I think this change is good to go. It's minimal, but a clear improvement, IMHO.

**Pull request merged**
